name: Build Site
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '>=24'
          # cache: 'npm'

      - name: Setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Change branch
        run: |
          git checkout live
          git checkout main -- ./
          git reset

      - name: Install packages
        run: npm install

      - name: Run build
        run: npm run build

      - name: Commit and push changes
        run: |
          git add ./docs -f
          git commit -m "Build for publishing"
          git push